#!/usr/bin/env node

import fs from "node:fs";

function stripJSONC(src) {
  // remove /* ... */ comments
  src = src.replace(/\/\*[\s\S]*?\*\//g, "");
  // remove // ... comments (not inside strings)
  src = src.replace(/(^|[^:])\/\/[^\n\r]*/g, "$1");
  return src;
}

const input =
  process.argv[2] && process.argv[2] !== "-"
    ? fs.readFileSync(process.argv[2], "utf8")
    : fs.readFileSync(0, "utf8");

process.stdout.write(stripJSONC(input));
