#!/usr/bin/env bash
set -e

GIT_SHA=$(git rev-parse HEAD)
STAGED_DIFF=$(git diff --cached --name-only | sort | xargs git diff --cached --unified=0)
UNSTAGED_DIFF=$(git diff --name-only | sort | xargs git diff --unified=0)
DIFF="$STAGED_DIFF$UNSTAGED_DIFF"

if [ -z "$DIFF" ]; then
  echo "$GIT_SHA"
else
  echo "${GIT_SHA}-$(echo "$DIFF" | sha256sum | awk '{print $1}')"
fi
